### ISSUE TITLE
`todo!` macro not re-exported from std

### ISSUE THREAD

**Issue by jplatte** [jhpratt/standback#1]
Using `standback::todo` only works with Rust < 1.40.

**Comment by jhpratt** [comment]
Ah, this should actually be in the prelude, since it doesn't need to be explicitly imported in new compilers.

**Comment by jhpratt** [comment]
Changes are on master. I just re-exported `unimplemented!` as `todo!` in the prelude, which is valid behavior per the documentation in `std`.
